--Create table PERSON_REGISTRATION
CREATE TABLE PERSON_REGISTRATION(
person_id  INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
first_name VARCHAR2(50) NOT NULL,
last_name VARCHAR2(50) NOT NULL,
email_id Varchar(70),
phone_number NUMBER
);
drop table person_registration

--insert 
INSERT INTO PERSON_REGISTRATION 
VALUES (NULL,'Dave', 'Badger', 'dave.b@email.com', 9876543210);
INSERT INTO PERSON_REGISTRATION 
VALUES (NULL,'John', 'David', 'john.d@email.com', 9432104895);
INSERT INTO PERSON_REGISTRATION 
VALUES (NULL,'Ruth', 'Fox', 'ruth.f@yahoo.com', 7894561230);
INSERT INTO PERSON_REGISTRATION 
VALUES (NULL,'Isabelle', 'Squirrel', 'isabel@mail.com', 8795462130);
INSERT INTO PERSON_REGISTRATION 
VALUES (NULL,'Justin', 'Frog', 'justin@gmail.com', 8502963741);
INSERT INTO PERSON_REGISTRATION 
VALUES (NULL,'Lisa', 'Owl', 'lisa.owl@mail.com', 8795462130);

select * from PERSON_REGISTRATION;

--Create table LOGIN
CREATE TABLE LOGIN ( 
  login_id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
  person_person_id INT NOT NULL,
  user_name VARCHAR2(50) NOT NULL,
  password VARCHAR2(50) NOT NULL,
  full_name VARCHAR2(50) NOT NULL,
  user_type VARCHAR2(50) NOT NULL  
);

drop table LOGIN

--Alter table LOGIN
ALTER TABLE LOGIN
ADD FOREIGN KEY (person_person_id) REFERENCES PERSON_REGISTRATION(person_id);

--insert 
INSERT INTO LOGIN 
VALUES (NULL,1,'davebadger', 'dave@123', 'Dave Badger', 'admin');
INSERT INTO LOGIN 
VALUES (NULL,2,'johnd', 'john@123', 'John David', 'admin');
INSERT INTO LOGIN 
VALUES (NULL,3,'ruthfox', 'ruth@123', 'Ruth Fox', 'normaluser');
INSERT INTO LOGIN 
VALUES (NULL,4,'isabel', 'isabel@123', 'Isabel Squirrel', 'normaluser');

select * from LOGIN;


--Create table PROJECT
CREATE TABLE PROJECT ( 
  project_id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
  login_login_id INT NOT NULL,
  project_name VARCHAR2(50) NOT NULL,
  assignee_name VARCHAR2(50) NOT NULL,
  start_date DATE,
  end_date DATE  
);
--Alter table PROJECT
ALTER TABLE PROJECT
ADD FOREIGN KEY (login_login_id) REFERENCES LOGIN(login_id);

--insert 
INSERT INTO PROJECT 
VALUES (NULL,1,'Pro', 'Ruth Fox', '01-JAN-2015', '10-MAY-2023');
INSERT INTO PROJECT 
VALUES (NULL,2,'Gordian', 'Isabel Squirrel', '04-APR-2021', '18-NOV-2025');

select * from PROJECT;
drop table PROJECT


--Create table TASK
CREATE TABLE TASK ( 
  task_id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
  project_project_id INT NOT NULL,
  task_name VARCHAR2(50) NOT NULL,
  task_status VARCHAR2(50) NOT NULL 
);



--Alter table TASK
ALTER TABLE 
ADD FOREIGN KEY (project_project_id) REFERENCES PROJECT(project_id);

INSERT INTO TASK 
VALUES (NULL,1,'Login', 'Open');
INSERT INTO TASK 
VALUES (NULL,2,'Registration', 'In Progress');

select * from TASK;

drop table TASK
































